### ISSUE TITLE
refactor : 메인 페이지 화면 리팩토링 하기

### ISSUE THREAD

**Issue by cgk95** [Kernel360/E2E1-KernelEngine#41]
## TODO
- [ ] 전체적인 스타일 맞추기
- [ ] 로고.png 보이도록 수정하기
- [ ] 피드 블럭 눌렀을 때 리다이렉션 하기
- [ ] 생성일에서 시간 떼기(날짜만 보여주기)
- [ ] 예쁘게 정렬하기
